CREATE DATABASE NLP_DATASTORE;
USE  NLP_DATASTORE;

CREATE TABLE NLP_RESULT_DOC (
	RESULT_DOC_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
	RUN_ID INTEGER,
	NLP_INPUT_ID INTEGER,
	RPT_ID VARCHAR(50),
	DOC_SRC VARCHAR(50),
	NLP_PIPELINE_ID INTEGER,
	RESULT VARCHAR(255),
	RESULT_DETAIL VARCHAR(255),
	RESULT_FEATURES VARCHAR(500),
	RESULT_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	RESULT_TYPE_ID INTEGER,
    PRIMARY KEY (RESULT_DOC_ID)
) ;

CREATE TABLE NLP_PIPELINE_DEF (
    PIPELINE_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
	PIPELINE_NAME VARCHAR(255),
	PIPELINE_DESCRIPTION VARCHAR(2000),
	PIPELINE_STATUS VARCHAR(50),
	ENTERED_DTM DATE,
    PRIMARY KEY (PIPELINE_ID)
) ;



CREATE TABLE NLP_RESULT_SNIPPET (
	SNIPPET_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
	RESULT_DOC_ID MEDIUMINT,
	SNIPPET_1 VARCHAR(2000),
	TERM_SEARCHED VARCHAR(500),
	MENTION_TYPE VARCHAR(200),
	TERM_SNIPPET_1_START_LOC INTEGER,
	TERM_SNIPPET_1_END_LOC INTEGER,
	TERM_START_LOC_DOCUMENT INTEGER,
	TERM_END_LOC_DOCUMENT INTEGER,
	MENTION_FEATURES VARCHAR(800),
    PRIMARY KEY (SNIPPET_ID),
	INDEX doc_ind (RESULT_DOC_ID),
	FOREIGN KEY (RESULT_DOC_ID)
        REFERENCES NLP_RESULT_DOC(RESULT_DOC_ID)
) ;

CREATE TABLE NLP_RESULT_FEATURES (
	RESULT_FEATURE_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    SNIPPET_ID MEDIUMINT,
	RESULT_DOC_ID MEDIUMINT,
	FEATURE_NAME VARCHAR(255),
	FEATURE_VALUE VARCHAR(1000),
    FEATURE_VALUE_NUMERIC VARCHAR(1000),
    PRIMARY KEY (RESULT_FEATURE_ID),
    INDEX doc_ind (RESULT_DOC_ID),
	FOREIGN KEY (RESULT_DOC_ID)
        REFERENCES NLP_RESULT_DOC(RESULT_DOC_ID),
	FOREIGN KEY (SNIPPET_ID)
        REFERENCES NLP_RESULT_SNIPPET(SNIPPET_ID)
) ;

CREATE TABLE NLP_RUN_DEF (
	RUN_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
	RUN_NAME VARCHAR(255),
	RUN_DESCRIPTION VARCHAR(255),
    PRIMARY KEY (RUN_ID)
) ;

