CREATE TABLE NLP_PIPELINE_DEF (
    PIPELINE_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
	PIPELINE_NAME VARCHAR(255),
	PIPELINE_DESCRIPTION VARCHAR(2000),
	PIPELINE_STATUS VARCHAR(50),
	ENTERED_DTM DATE,
    PRIMARY KEY (PIPELINE_ID)
) ;