CREATE TABLE NLP_RESULT_SNIPPET (
	SNIPPET_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
	RESULT_DOC_ID MEDIUMINT,
	SNIPPET_1 VARCHAR(2000),
	-- SNIPPET_2 VARCHAR(2000),
	TERM_SEARCHED VARCHAR(500),
	MENTION_TYPE VARCHAR(200),
	TERM_SNIPPET_1_START_LOC INTEGER,
	TERM_SNIPPET_1_END_LOC INTEGER,
	-- TERM_SNIPPET_2_START_LOC INTEGER,
	-- TERM_SNIPPET_2_END_LOC INTEGER,
	TERM_START_LOC_DOCUMENT INTEGER,
	TERM_END_LOC_DOCUMENT INTEGER,
	MULTISPAN_ANNOTATION VARCHAR(500),
	VARIABLE_URI VARCHAR(500),
	MENTION_FEATURES VARCHAR(800),
    PRIMARY KEY (SNIPPET_ID),
	INDEX doc_ind (RESULT_DOC_ID),
	FOREIGN KEY (RESULT_DOC_ID)
        REFERENCES NLP_RESULT_DOC(RESULT_DOC_ID)
) ;
