CREATE TABLE NLP_RESULT_DOC (
	RESULT_DOC_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
	RUN_ID INTEGER,
	NLP_INPUT_ID INTEGER,
	RPT_ID VARCHAR(50),
	DOC_SRC VARCHAR(50),
	NLP_PIPELINE_ID INTEGER,
	RESULT VARCHAR(255),
	RESULT_DETAIL VARCHAR(255),
	RESULT_FEATURES VARCHAR(500),
	RESULT_DTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	RESULT_TYPE_ID INTEGER,
    PRIMARY KEY (RESULT_DOC_ID)
) ;
